### ISSUE TITLE
Likely my system... 

### ISSUE THREAD

**Issue by MichaelCade** [fabianlee/k3s-cluster-kvm#1]
I am getting a fatal error on local packaged needed for ipaddr jinja2 filter 

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python-netaddr' is available"}`

If i then check netaddr is present i get 

`pip3 install netaddr
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: netaddr in /usr/lib/python3/dist-packages (0.8.0)`

**Comment by fabianlee** [comment]
Have you run:
```
ansible-playbook install_dependencies.yml
```

Because the pip modules are required, but it also requires the OS level packages.
https://github.com/fabianlee/k3s-cluster-kvm/blob/main/install_dependencies.yml#L42

**Comment by MichaelCade** [comment]
`michael@HomeLab01:~/Documents/k3s-cluster-kvm$ ansible-playbook install_dependencies.yml

PLAY [localhost] *************************************************************************************************************************
TASK [Gathering Facts] *******************************************************************************************************************ok: [localhost]

TASK [fetch k3s ansible role from github] ************************************************************************************************changed: [localhost]

TASK [make collections directory] ********************************************************************************************************changed: [localhost]

TASK [get community.kubernetes collection from ansible galaxy, be patient can take 5 minutes] ********************************************changed: [localhost]

TASK [get community.crypto collection from ansible galaxy, be patient can take 5 minutes] ************************************************
changed: [localhost]

TASK [install local packages needed for ipaddr jinja2 filter] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python-netaddr' is available"}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

**Comment by fabianlee** [comment]
What version of Debian/Ubuntu are you on:

```
lsb_release -a
```

**Comment by MichaelCade** [comment]
`Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
`

**Comment by MichaelCade** [comment]
Having worked through a little more I am also finding that it seems the qemu resize commands are also not working on the nodes as i am left with 2.2GB which is filling up as I think expected. Working through to make sure it is not just me though.

**Comment by MichaelCade** [comment]
Could have again just have been my system but it looks like the terraform change of disk size did not happen. I manually powered down the machine and used `sudo qemu-img resize k3s-1.qcow2 10G` and this resized and let me continue.

**Comment by fabianlee** [comment]
I recreated the original issue on a fresh Ubuntu 22.04 installation.

I just checked-in conditionals for that OS package, updated the version of the community.general package that was throwing errors, and added a unit test for the netaddr module.

```
git pull -r
ansible-playbook install_dependencies.yml
ansible-playbook tests/ipaddr_filter.yml
```

**Comment by MichaelCade** [comment]
Sure let me trash and go again

**Comment by MichaelCade** [comment]
Ran through with the following outcome: 

`░▒▓ ~/Documents/HomeLab/k3s-cluster-kvm  main *1 ▓▒░ ansible-playbook install_dependencies.yml                                                                                   ░▒▓ ✔  16:20:05 ▓▒░

PLAY [localhost] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "OS release=jammy, OS version=22.04"
}

TASK [fetch k3s ansible role from github] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [make collections directory] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [get community.kubernetes collection from ansible galaxy, be patient can take 5 minutes] *******************************************************************************************************
ok: [localhost]

TASK [get community.crypto collection from ansible galaxy, be patient can take 5 minutes] ***********************************************************************************************************
ok: [localhost]

TASK [install local packages needed for ipaddr jinja2 filter] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ******************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
`
I can fix this using the below --ask-become-pass command: 

`░▒▓ ~/Documents/HomeLab/k3s-cluster-kvm  main *1 ▓▒░ ansible-playbook install_dependencies.yml --ask-become-pass `

**Comment by MichaelCade** [comment]
Next issue related to space above 

TASK [k9s : move k9s binary to PATH] ****************************************************************************************************************************************************************
fatal: [k3s-1]: FAILED! => {"changed": false, "msg": "failed to copy: /tmp/k9s to /usr/local/bin/k9s", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_3ffrx5uq/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 687, in main\n  File \"/usr/lib/python3.8/shutil.py\", line 275, in copyfile\n    _fastcopy_sendfile(fsrc, fdst)\n  File \"/usr/lib/python3.8/shutil.py\", line 166, in _fastcopy_sendfile\n    raise err from None\n  File \"/usr/lib/python3.8/shutil.py\", line 152, in _fastcopy_sendfile\n    sent = os.sendfile(outfd, infd, offset, blocksize)\nOSError: [Errno 28] No space left on device: b'/tmp/k9s' -> b'/usr/local/bin/tmp2496lwp6'\n"}

**Comment by MichaelCade** [comment]
Adding NFS mount and sharing amongst the K3s nodes, the following is done on the host (localhost) 

░▒▓ ~ ▓▒░ sudo mkdir /data/nfs1 -p                                                                                                                                                
░▒▓ ~ ▓▒░ sudo chown nobody:nogroup /data/nfs1                                                                                                                                    
░▒▓ ~ ▓▒░ sudo nano /etc/exports                                                                                                                                                  
░▒▓ ~ ▓▒░ sudo systemctl restart nfs-kernel-server                                                                              

etc/exports for now looks like this: 

/data/nfs1          *(rw,sync,no_subtree_check)

Best practice would be to add in specific node IPs

**Comment by fabianlee** [comment]
The guest OS disks were not being resized by qemu-img because the script must use sudo (because of permissions on file created by libvirt).

Added instructions on the [blog page](https://fabianlee.org/2021/09/12/kubernetes-k3s-cluster-on-ubuntu-using-ansible/):
- to change the permissions on the default pool directory and files
- to run a sudo command right before playbook_k3s_prereq.yaml, which will avoid password prompt during playbook

Added instructions on README:
- to run a sudo command right before playbook_k3s_prereq.yaml, which will avoid password prompt during playbook

**I'm closing now, thanks for the feedback and testing.  This was originally developed/tested on Ubuntu 18.04, but now I have done the same on a fresh Ubuntu 22.04.**


For changing permissions of default data pool directory
```
pool_dir=$(virsh pool-dumpxml default | grep -Po '<path>\K[^<]+')
sudo chgrp -R libvirt $pool_dir
sudo chmod g+rws $pool_dir
sudo ls -ld $pool_dir
```
