### ISSUE TITLE
Typo in prometheus config?

### ISSUE THREAD

**Issue by RichardSufliarsky** [fabianlee/k3s-cluster-kvm#2]
Thanks for the article: https://fabianlee.org/2022/07/08/prometheus-monitoring-services-using-additional-scrape-config-for-prometheus-operator/

I used additional scrape config for the pods and I think that this line https://github.com/fabianlee/k3s-cluster-kvm/blob/c852d617173dd52f384b34fdd4874e6755c08717/roles/kube-prometheus-stack/files/prom-sparse.expanded.yaml#L180 should use \_\_meta\_kubernetes\_**pod**\_name

**Comment by fabianlee** [comment]
thanks! changed
